spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.19.133.126:9092,10.19.133.126:9093,10.19.133.126:9094         #Kafka的消息中间件服务器
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        MyOutPut: #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: ax2SyncEventOutput    #消息发往的目的地
          content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
        input:
          destination: ax2SyncEventOutput    #消息发往的目的地
          group: wsl
  redis:
    host: 10.19.133.122
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  datasource:
    url: jdbc:mysql://10.19.133.122:3306/sys?useUnicode=true&characterEncoding=utf8
    username: convergence_cloud
    password: MIGfMA0GCSqGSIb3DQEB
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #初始化大小
      initial-size: 5
      min-idle: 5
      #最大活跃连接数
      max-active: 50
      #链接最长等待时间
      max-wait: 200
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 打开PSCache
      poolPreparedStatements: true
      # 单个链接的PSCache大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 单个连接最小生存的时间单位毫秒
      min-evictable-idle-time-millis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #监控统计拦截的filtes
      filters: stat,wall
      #打开mergeSql功能，记录慢Sql
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      #配置filter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    jpa:
      database: mysql
      show-sql: false
      generate-ddl: false
      hibernate:
        ddl-auto: none
  mvc:
    view:
      suffix:



server:
  port: 8080